# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='description',
            new_name='interests',
        ),
    ]
